### ISSUE TITLE
Target uncertainty calculation

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/open-forcefield-tools#12]
Question for @davidlmobley and @mrshirts:

The current strategy for `PropertyEstimator.computeProperties()` will be, for each property requested and parameter set:
- First, try to estimate the property using available data
- If no data exists, or if the property estimate uncertainty exceeds the threshold, run the simulation at the specified thermodynamic parameters until the uncertainty falls below this threshold

My question is this: **What uncertainty threshold should we use for this, and how much flexibility should we give the user over it?** 

My original idea was to fix this at, say, 0.1 times the experimental uncertainty (to ensure that our Bayesian likelihood functions are meaningful). Does this sound reasonable, and would you still like control over this (in case you want to make it more or less strict)?

**Comment by jchodera** [comment]
Also, is this relative uncertainty (based on experimental uncertainty) an OK way to specify this, or do you need more control?

**Comment by davidlmobley** [comment]
I think that's a great default target, and I think you should allow us to
override that. Seems like it would be nice to be able to override by
providing either (a) a multiple of the experimental uncertainty to hit, or
(b) an absolute target uncertainty - for example, if I was doing density
calculations for a big set of compounds and I wanted to be able to report
all of them to 1e-5 g/cm^3 for consistency across the set, it'd be annoying
to have to specify it for all of them in units of variable experimental
uncertainties....

David

On Mon, Jul 4, 2016 at 7:21 PM, John Chodera notifications@github.com
wrote:

> Also, is this relative uncertainty (based on experimental uncertainty) an
> OK way to specify this, or do you need more control?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-tools/issues/12#issuecomment-230374965,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYQuz8u0Xh6ewiGnyYAPkglds661Yks5qSb-YgaJpZM4JEuoz
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
I talked to @mrshirts and he agrees. There is a small concern that some calculations may be sufficiently costly that we may not be able to converge them that precisely in any reasonable amount of time, but we can cross that bridge when we come to it. Marking resolved.
