### ISSUE TITLE
Discuss choices to be made to get SMIRFF XML format into OpenMM

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/open-forcefield-tools#7]
@jchodera mentioned we should discuss some choices needing to be made to get between the SMIRFF XML format and OpenMM parameters, given a target molecule and the XML format parameters (https://github.com/open-forcefield-group/open-forcefield-data/issues/9).

@jchodera , what are those choices, so we can provide input?

**Comment by jchodera** [comment]
See https://github.com/open-forcefield-group/smarty/issues/18

**Comment by davidlmobley** [comment]
This was closed by the other issue and resulting creation of SMIRFF functionality in the smarty repo.
